name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check:
    name: "Tests / OS: ${{ matrix.os }} - ${{ matrix.channel }}-${{ matrix.rust_target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        exclude:
        - os: macos-10.15
          rust_target: x86_64-gnu
        - os: macos-10.15
          rust_target: x86_64-msvc
        - os: windows-2019
          rust_target: x86_64-apple-darwin
        - os: ubuntu-20.04
          rust_target: x86_64-msvc
        - os: ubuntu-20.04
          rust_target: x86_64-apple-darwin
        channel:
        - stable
        - beta
        - nightly
        os:
        - macos-10.15
        - windows-2019
        - ubuntu-20.04
        rust_target:
        - x86_64-gnu
        - x86_64-msvc
        - x86_64-apple-darwin

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - name: Install Rust Toolchain
      run: rustup default ${{ matrix.channel }}-${{ matrix.rust_target }}

    - name: Install cargo-hack
      run: cargo install cargo-hack

    - name: Powerset
      run: cargo hack test --feature-powerset --lib --optional-deps --depth 3 --skip "compiler_builtins core rustc-dep-of-std"

    - name: Docs
      run: cargo doc --features example_generated

    - name: Smoke test
      run: cargo run --manifest-path tests/smoke-test/Cargo.toml

  benches:
    name: Benches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Rust toolchain
        run: rustup default nightly

      - name: Default features
        run: cargo bench --no-run

  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install tombl
        run: cargo install tombl

      - name: Smoke test
        run: |
          eval $(tombl -e msrv=package.rust-version Cargo.toml)
          rustup update $msrv
          cd ./tests/smoke-test
          cargo +$msrv build

  embedded:
    name: Build (embedded)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Rust toolchain
        run: |
          rustup default nightly
          rustup target add thumbv6m-none-eabi

      - name: Default features
        run: cargo build -Z avoid-dev-deps --features example_generated --target thumbv6m-none-eabi
